<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>source.js$, source.js meta.function.body$</string>
	<key>name</key>
	<string>JavaScript @jsx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^/\*\* @jsx React.DOM \*/$</string>
			<key>name</key>
			<string>invalid.illegal.DEBUG</string>
		</dict>
	</array>
	<key>uuid</key>
	<string>539F81FB-0AF8-432D-A9DE-184035228A39</string>
</dict>
</plist>
