<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsx</string>
		<string>react.js</string>
	</array>
	<key>firstLineMatch</key>
	<string>@jsx</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaScript with XML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.es6</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.es6</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.es6</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[\s\S]</string>
					<key>name</key>
					<string>constant.character.escape.es</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.es6</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.js.jsx</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.es6</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.expression.es6</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.readwrite.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.typescriptish</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.typescriptish</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.name</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.something</string>
				</dict>
			</dict>
			<key>disabled</key>
			<integer>1</integer>
			<key>match</key>
			<string>([_$a-zA-Z][_$a-zA-Z0-9]*)(\s*(:)\s*([_$a-zA-Z][_$a-zA-Z0-9]*)(?:&lt;([^&gt;]*)&gt;)?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.readwrite.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.typescriptish</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_$a-zA-Z][_$a-zA-Z0-9]*)\s*(&lt;[^&gt;]*&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.begin.hack</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.end.hack</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/\*)(?:\??[_$a-zA-Z0-9]+(?:&lt;[^&gt;]+&gt;)?\|?)+(\*/ )</string>
			<key>name</key>
			<string>storage.type.class.hack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[_$a-zA-Z0-9\)\]\}&gt;])\s*&lt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_tag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;(\w+))</string>
			<key>disabled</key>
			<integer>1</integer>
			<key>end</key>
			<string>(?&lt;=/&gt;)|(?&lt;=&lt;/\1&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html.jsx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.html.embedded.$1.jsx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.5</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.begin.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>12.1 Block http://es5.github.com/#x12.1</string>
			<key>contentName</key>
			<string>meta.block.es</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.end.es</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|(?:get|set)(?=\s+[_$a-zA-Z]))\b(?:\s+((?i)[_$a-z][_$a-z0-9]*))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.es</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.$1.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>13 Function Definition http://es5.github.com/#x13</string>
			<key>end</key>
			<string>(?&lt;=})</string>
			<key>name</key>
			<string>meta.$1.${2:-unnamed}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(?!\()</string>
							<key>comment</key>
							<string>function name</string>
							<key>end</key>
							<string>(?=\()</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b(?i)[_$a-z][_$a-z0-9]*\b</string>
									<key>name</key>
									<string>entity.name.function.$1.es</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.function.es</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>function parameters</string>
							<key>contentName</key>
							<string>meta.function.parameters</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.end.function.es</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.function.parameters</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b(?i)[_$a-z][_$a-z0-9]*\b</string>
									<key>name</key>
									<string>variable.parameter.function.es</string>
								</dict>
								<dict>
									<key>match</key>
									<string>,</string>
									<key>name</key>
									<string>punctuation.separator.parameters.function.es</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.begin.es</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>function body</string>
					<key>contentName</key>
					<string>meta.function.body</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.end.es</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=(&lt;)([a-zA-Z0-9_$][^\s&lt;/&gt;]*))</string>
					<key>contentName</key>
					<string>meta.block.inner.${2/[:.]/-/g}.jsx</string>
					<key>end</key>
					<string>(&lt;/)(\2)(&gt;)|(/&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.end.${2/[:.]/-/g}.jsx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.${2/[:.]/-/g}.jsx</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.begin.${2/[:.]/-/g}.jsx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.tag.block.${2/[:.]/-/g}.jsx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(&lt;)([^\s&lt;/&gt;]+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.${2/[:.]/-/g}.jsx</string>
								</dict>
							</dict>
							<key>end</key>
							<string>&gt;|(?=/&gt;)</string>
							<key>name</key>
							<string>meta.tag.block.begin.${2/[:.]/-/g}.jsx</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attr</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=[^/]&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/)</string>
							<key>name</key>
							<string>meta.scope.jsx</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#block_tag</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.jsx</string>
	<key>uuid</key>
	<string>6DAD38D9-0DCB-4F22-9EE6-4D1F3BBE3C5B</string>
</dict>
</plist>
