<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsx</string>
		<string>react.js</string>
	</array>
	<key>firstLineMatch</key>
	<string>@jsx</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaScript with JSX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.es6</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.es6</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.es6</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[\s\S]</string>
					<key>name</key>
					<string>constant.character.escape.es</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.es6</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.js.jsx</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.es6</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.expression.es6</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.begin.hack</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.end.hack</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/\*)(?:\??[_$a-zA-Z0-9]+(?:&lt;[^&gt;]+&gt;)?\|?)+(\*/ )</string>
			<key>name</key>
			<string>storage.type.class.hack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[_$a-zA-Z0-9\)\]\}&gt;])\s*&lt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_tag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.begin.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>12.1 Block http://es5.github.com/#x12.1</string>
			<key>contentName</key>
			<string>meta.block.es</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.end.es</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(class)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.es</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.class.es</string>
			<key>end</key>
			<string>(?&lt;=})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.begin.es</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>class body</string>
					<key>contentName</key>
					<string>meta.class.body.es</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.end.es</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#method</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#class-property</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.$1.es</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.es</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.function.parameters</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.es</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.arrow.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>14.2 Arrow Function Definitions http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions</string>
			<key>match</key>
			<string>(?:([_$a-z][_$a-z0-9]*)\s*(=)\s*)?\b(?i)(([_$a-z][_$a-z0-9]*))\b\s*(=&gt;)\s?</string>
			<key>name</key>
			<string>meta.function.arrow.${1:-unnamed}.with-only-one-arg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(=&gt;) ({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.arrow.es</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.begin.es</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.arrow.innards.es</string>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.end.es</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.arrow.es</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|(?:get|set)(?=\s+[_$a-zA-Z]))\b(?:\s+((?i)[_$a-z][_$a-z0-9]*))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.es</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.$1.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>13 Function Definition http://es5.github.com/#x13</string>
			<key>end</key>
			<string>(?&lt;=})</string>
			<key>name</key>
			<string>meta.$1.${2:-unnamed}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(?!\()</string>
							<key>comment</key>
							<string>function name</string>
							<key>end</key>
							<string>(?=\()</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b(?i)[_$a-z][_$a-z0-9]*\b</string>
									<key>name</key>
									<string>entity.name.function.$1.es</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-params</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\))(?!\{)</string>
					<key>end</key>
					<string>(?=\{)</string>
					<key>name</key>
					<string>meta.directive.return-type.flow</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=&gt;</string>
							<key>name</key>
							<string>invalid.illegal.arrow</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type-def</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.begin.es</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>function body</string>
					<key>contentName</key>
					<string>meta.function.body</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.end.es</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.arrow.es</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(=&gt;)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(return)\s+</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\.)?(\b(?i)[_$a-z][_$a-z0-9]*\b)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.method.call.es</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.call.$2.es</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.es</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.es</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function-call.$2.es</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#round</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;/([^&gt;]*)&gt;</string>
					<key>name</key>
					<string>invalid.illegal.tag.end.${1/[:.]/-/g}.jsx</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=(&lt;)([a-zA-Z0-9_$][^\s&lt;/&gt;]*))</string>
					<key>end</key>
					<string>(&lt;/)(\2)(&gt;)|(/&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.end.${2/[:.]/-/g}.jsx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.${2/[:.]/-/g}.jsx</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.begin.${2/[:.]/-/g}.jsx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.tag.block.${2/[:.]/-/g}.jsx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(&lt;)([^\s&lt;/&gt;]+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.${2/[:.]/-/g}.jsx</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(&gt;)|(?=/&gt;)</string>
							<key>name</key>
							<string>meta.tag.block.begin.${2/[:.]/-/g}.jsx</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attr</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>&lt;/([^&gt;]*)&gt;</string>
							<key>name</key>
							<string>invalid.illegal.tag.end.${1/[:.]/-/g}.jsx</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&lt;(/[a-zA-Z0-9_$.]*)?($|\s)</string>
							<key>name</key>
							<string>invalid.illegal.tag.end.jsx</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=&gt;)(?!&lt;$)(?!&lt;\s)(?!&lt;/)</string>
							<key>end</key>
							<string>(?=&lt;/)</string>
							<key>name</key>
							<string>meta.scope.jsx</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#block_tag</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>class-property</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)([_$a-zA-Z][_$a-zA-Z0-9]*)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.class.es</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.flow</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,);])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>destructured-whatever</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.destructured.es</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.destructured.es</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.destructured.es</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.definition.parameters.separator.destructured.es</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#var-name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#destructured-whatever</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-params</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.function.es</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function parameters</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.function.es</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.parameters</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)[_$a-z][_$a-z0-9]*\b</string>
					<key>name</key>
					<string>variable.parameter.function.es</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-def</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.parameters.function.es</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>\b(?i)([_$a-z][_$a-z0-9]*)\b(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.method.es</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=})</string>
			<key>name</key>
			<string>meta.function.method.$1.es</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(?=\()</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-params</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nested-brackets</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\))(?!\{)</string>
					<key>end</key>
					<string>(?=\{)</string>
					<key>name</key>
					<string>meta.directive.return-type.flow</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=&gt;</string>
							<key>name</key>
							<string>invalid.illegal.arrow</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type-def</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.begin.es</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>function body</string>
					<key>contentName</key>
					<string>meta.function.body</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.end.es</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nested-brackets</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\}</string>
					<key>name</key>
					<string>invalid.illegal.brace</string>
				</dict>
			</array>
		</dict>
		<key>nested-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nested-brackets</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>round</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#round</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>type-def</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\??:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.flow</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,;&gt;(){}\[\]=])</string>
					<key>name</key>
					<string>meta.scope</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.optional.flow</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(\??)[_$a-zA-Z][_$a-zA-Z0-9]*</string>
					<key>name</key>
					<string>storage.type.flow</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(\??)[_$a-zA-Z][_$a-zA-Z0-9]*(&lt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.es</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.es</string>
						</dict>
					</dict>
					<key>name</key>
					<string>storage.type.flow</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=:)\s*(\??)\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.es</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>storage.type.flow</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>storage.type.flow</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(var|const|let)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.$1.es</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[;}])|$</string>
					<key>name</key>
					<string>meta.expression.es</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#var-part</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>,</string>
							<key>end</key>
							<string>(?=[,;}])</string>
							<key>name</key>
							<string>meta.scope.var</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#var-part</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#nested-brackets</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-name</key>
		<dict>
			<key>match</key>
			<string>(?i)[_$a-zA-Z][_$a-zA-Z0-9]*</string>
			<key>name</key>
			<string>variable.other.readwrite.js</string>
		</dict>
		<key>var-part</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#destructured-whatever</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-def</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.$1.es</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,;}])</string>
					<key>name</key>
					<string>meta.scope.var.right-side</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.jsx</string>
	<key>uuid</key>
	<string>6DAD38D9-0DCB-4F22-9EE6-4D1F3BBE3C5B</string>
</dict>
</plist>
