<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>source.js.jsx meta.tag.block.begin$</string>
	<key>name</key>
	<string>JSX attribute values</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\s*([_$a-zA-Z0-9][-_$a-zA-Z0-9]*)(=)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.$1.jsx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.attribute.jsx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.jsx</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.js.jsx</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.jsx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.expression.$1.jsx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js.jsx</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>([_$a-zA-Z0-9][-_$a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>entity.other.attribute-name.$1.jsx</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.jsx</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.scope.inner</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.jsx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.jsx</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.jsx</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.scope.inner</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.jsx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.jsx</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.jsx.attribute-values</string>
	<key>uuid</key>
	<string>4E87F1E0-BFD2-4857-8548-1E29D04D8B54</string>
</dict>
</plist>
